data_directory: "base" 
data_files_glob: "*.txt"
webpages:
  - "https://en.wikipedia.org/wiki/James_Webb_Space_Telescope"
  - "https://en.wikipedia.org/wiki/Black_hole"
  - "https://en.wikipedia.org/wiki/Roko%27s_basilisk"
tone: "formal"
persona: "buddha"
